<?php

namespace Database\Seeders;

use App\Enums\StatisticCategoryCode;
use App\Models\IndustryLocation;
use App\Models\StatisticCategory;
use Illuminate\Database\Seeder;

class IndustryLocationSeeder extends Seeder
{
    public function run(): void
    {
        $categories = StatisticCategory::query()->pluck('id', 'code');

        $locations = [
            [
                'category' => StatisticCategoryCode::KEK_KI->value,
                'name' => 'Kawasan Industri Jababeka',
                'slug' => 'kawasan-industri-jababeka',
                'industry_sector' => 'Manufaktur Campuran',
                'province' => 'Jawa Barat',
                'city' => 'Bekasi',
                'latitude' => -6.3187000,
                'longitude' => 107.1437000,
                'workforce' => 32500,
                'investment_value' => 1285000000000,
                'output_value' => 1640000000000,
                'status' => 'active',
                'address' => 'Cikarang, Bekasi',
                'notes' => 'Data dummy untuk simulasi peta KEK/KI.',
                'is_dummy' => true,
                'sort_order' => 1,
            ],
            [
                'category' => StatisticCategoryCode::KEK_KI->value,
                'name' => 'KEK Sei Mangkei',
                'slug' => 'kek-sei-mangkei',
                'industry_sector' => 'Pengolahan Agro',
                'province' => 'Sumatera Utara',
                'city' => 'Simalungun',
                'latitude' => 2.8665000,
                'longitude' => 99.2856000,
                'workforce' => 12400,
                'investment_value' => 750000000000,
                'output_value' => 980000000000,
                'status' => 'active',
                'address' => 'Bosar Maligas, Simalungun',
                'notes' => 'Dummy layer kawasan industri luar Jawa.',
                'is_dummy' => true,
                'sort_order' => 2,
            ],
            [
                'category' => StatisticCategoryCode::IBS->value,
                'name' => 'Klaster Otomotif Karawang',
                'slug' => 'klaster-otomotif-karawang',
                'industry_sector' => 'Otomotif',
                'province' => 'Jawa Barat',
                'city' => 'Karawang',
                'latitude' => -6.3054000,
                'longitude' => 107.3373000,
                'workforce' => 28750,
                'investment_value' => 2150000000000,
                'output_value' => 3240000000000,
                'status' => 'active',
                'address' => 'Karawang Barat',
                'notes' => 'Dummy sentra IBS sektor otomotif.',
                'is_dummy' => true,
                'sort_order' => 3,
            ],
            [
                'category' => StatisticCategoryCode::IBS->value,
                'name' => 'Pabrik Tekstil Bandung Raya',
                'slug' => 'pabrik-tekstil-bandung-raya',
                'industry_sector' => 'Tekstil',
                'province' => 'Jawa Barat',
                'city' => 'Bandung',
                'latitude' => -6.9147000,
                'longitude' => 107.6098000,
                'workforce' => 14200,
                'investment_value' => 425000000000,
                'output_value' => 690000000000,
                'status' => 'active',
                'address' => 'Bandung Raya',
                'notes' => 'Dummy untuk IBS berbasis tekstil.',
                'is_dummy' => true,
                'sort_order' => 4,
            ],
            [
                'category' => StatisticCategoryCode::IMK->value,
                'name' => 'Sentra Mebel Jepara',
                'slug' => 'sentra-mebel-jepara',
                'industry_sector' => 'Kerajinan Kayu',
                'province' => 'Jawa Tengah',
                'city' => 'Jepara',
                'latitude' => -6.5924000,
                'longitude' => 110.6685000,
                'workforce' => 5400,
                'investment_value' => 98000000000,
                'output_value' => 154000000000,
                'status' => 'active',
                'address' => 'Jepara',
                'notes' => 'Dummy sentra IMK tradisional.',
                'is_dummy' => true,
                'sort_order' => 5,
            ],
            [
                'category' => StatisticCategoryCode::IMK->value,
                'name' => 'Sentra Kerajinan Bantul',
                'slug' => 'sentra-kerajinan-bantul',
                'industry_sector' => 'Kriya dan Furnitur',
                'province' => 'DI Yogyakarta',
                'city' => 'Bantul',
                'latitude' => -7.8886000,
                'longitude' => 110.3284000,
                'workforce' => 3200,
                'investment_value' => 56000000000,
                'output_value' => 87000000000,
                'status' => 'active',
                'address' => 'Bantul',
                'notes' => 'Dummy IMK wilayah DIY.',
                'is_dummy' => true,
                'sort_order' => 6,
            ],
            [
                'category' => StatisticCategoryCode::DSI->value,
                'name' => 'Industri Pangan Surabaya',
                'slug' => 'industri-pangan-surabaya',
                'industry_sector' => 'Makanan dan Minuman',
                'province' => 'Jawa Timur',
                'city' => 'Surabaya',
                'latitude' => -7.2575000,
                'longitude' => 112.7521000,
                'workforce' => 11800,
                'investment_value' => 650000000000,
                'output_value' => 910000000000,
                'status' => 'active',
                'address' => 'Surabaya',
                'notes' => 'Dummy ringkasan DSI untuk sektor makanan.',
                'is_dummy' => true,
                'sort_order' => 7,
            ],
            [
                'category' => StatisticCategoryCode::DSI->value,
                'name' => 'Industri Pengolahan Sawit Medan',
                'slug' => 'industri-pengolahan-sawit-medan',
                'industry_sector' => 'Agroindustri',
                'province' => 'Sumatera Utara',
                'city' => 'Medan',
                'latitude' => 3.5952000,
                'longitude' => 98.6722000,
                'workforce' => 9600,
                'investment_value' => 575000000000,
                'output_value' => 830000000000,
                'status' => 'active',
                'address' => 'Medan',
                'notes' => 'Dummy lokasi industri pengolahan luar Jawa.',
                'is_dummy' => true,
                'sort_order' => 8,
            ],
        ];

        foreach ($locations as $location) {
            IndustryLocation::updateOrCreate(
                ['slug' => $location['slug']],
                [
                    'statistic_category_id' => $categories[$location['category']] ?? null,
                    'name' => $location['name'],
                    'industry_sector' => $location['industry_sector'],
                    'province' => $location['province'],
                    'city' => $location['city'],
                    'latitude' => $location['latitude'],
                    'longitude' => $location['longitude'],
                    'workforce' => $location['workforce'],
                    'investment_value' => $location['investment_value'],
                    'output_value' => $location['output_value'],
                    'status' => $location['status'],
                    'address' => $location['address'],
                    'notes' => $location['notes'],
                    'is_dummy' => $location['is_dummy'],
                    'sort_order' => $location['sort_order'],
                ],
            );
        }
    }
}
